# Generated by Django 5.0.1 on 2024-01-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_cartitem_date_added_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='mohan',
            new_name='user',
        ),
    ]
